### ISSUE TITLE
Question about merging and pull requests.

### ISSUE THREAD

**Issue by Wjandr** [kevinaangstadt/CS340-S23-Notes#146]
Should we be merging all the changes from main into our branches before committing?
Basically what I'm wondering is if the branch I create the pull request for only has my Day26Notes.md file in it, will this cause other files to be removed from main if my PR is accepted?

**Comment by kevinaangstadt** [comment]
It should not cause the other files to be removed, you you need to verify that your PR can merge into the main branch. This might require a merge of the commits.
