### ISSUE TITLE
Creating the Additional Pull Request

### ISSUE THREAD

**Issue by AidanMarler123** [kevinaangstadt/CS340-S23-Notes#147]
I was wondering if we needed to wait for our pull requests to be verified/approved before we can fork them and edit them for contribution. I can't seem to figure out how to fork (or gain access to) a pull request that hasn't been approved. Let me know if anyone has a solution to this or any comments on this.

**Comment by kevinaangstadt** [comment]
If you want to make changes on this repo, you need to wait for the PR to be merged.
