### ISSUE TITLE
Style_Guide

### ISSUE THREAD

**Issue by rmfust20** [kevinaangstadt/CS340-S23-Notes#36]
Hey everyone,

It would probably be a good idea if we could all agree on a universal style sheet for our lecture notes.

Things to consider could be :

- Font style
- Font size
- Headers
- If we should include our name at the top
- Title inside the document that outlines the topics covered
- Spacing

The style guide hasn't been claimed by anyone yet, so maybe a few of us should get together and sort this out before people start submitting notes.

**Comment by CharlesReinhardt** [comment]
It looks like Ben is going to work on the style guide. We should direct any suggestions and ideas to him on issue #83

**Comment by kevinaangstadt** [comment]
Closing this in favor of #83.  (This conversation will remain linked)
