### ISSUE TITLE
Committing from specific branches vs Main branch

### ISSUE THREAD

**Issue by mattabell03** [kevinaangstadt/CS340-S23-Notes#40]
I noticed some people are making separate branches in their forked copies of the repo and committing from those, while some other people are committing from their Main branches. Does it matter which option we use? Would that only affect local repository organization?

**Comment by kevinaangstadt** [comment]
Committing from branches is slightly better.  This way, if you are working on multiple changes at the same time, your commits can be shared with specific PRs
