### ISSUE TITLE
Forked Main Repo Question

### ISSUE THREAD

**Issue by jmange19** [kevinaangstadt/CS340-S23-Notes#53]
Is it problematic if my main repository contains more files than the original repository?
That is, should I delete the lecture 4 outline in my main branch, since I created a day 4 branch for it?

**Comment by LeifHarvey** [comment]
Yes, since the spec says to "create your pull requests from non-main branches," it is best to do all your work on a separate branch.

**Comment by kevinaangstadt** [comment]
You will generally want to contribute from separate branches that focus on the specific change you are making. This avoids issues where commits make their way into unrelated PRs.
