### ISSUE TITLE
Graphics in Notes

### ISSUE THREAD

**Issue by JamesB5201** [kevinaangstadt/CS340-S23-Notes#68]
After looking back in my notes, I noticed that there are some lectures that contain diagrams in the notes that are helpful to know. However, I don't know how we would go about implementing these diagrams into our notes, because we would not be able to imbed the image directly into the notes file. Does anyone have any suggestions on how we can include these diagrams, or would it be for the best to just ignore them?

**Comment by kevinaangstadt** [comment]
[Writing on Github](https://docs.github.com/en/get-started/writing-on-github) might be of help.  It's also possible to embed images (but they would have to be committed as well).
