### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by mogulmax** [kevinaangstadt/CS340-S23-Notes#75]
Hey I noticed file some file names are different, some have lecturex.md and others have lecturex_date.md. We should all try to stay consistent. I did mine without the date, what seems better to you guys?

**Comment by LeifHarvey** [comment]
Using lecture#.md seems to me like a good format to follow as it is cleaner and more concise than a full date.

**Comment by kevinaangstadt** [comment]
Closing as duplicate of #38
